use std::path::{Path, PathBuf};

const FLAVOR: &str = "luajit";
const CSHARP_NAMESPACE: &str = "NuLua.Interop.LuaJit";
const CSHARP_CLASS: &str = "NativeMethods";
const CSHARP_PROJECT: &str = "NuLua.Interop.LuaJit";

// NOTE: LuaJIT requires running its host `buildvm` step (Makefile-driven) to
// generate intermediate sources before the runtime can be compiled. That is
// not handled here yet — only the C# binding surface is generated from the
// public headers. cdylib linking will be wired in once buildvm orchestration
// is in place.
fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir.parent().unwrap().parent().unwrap().to_path_buf();
    let luajit_root = workspace_root.join("submodules").join("luajit");
    let header_dir = luajit_root.join("src");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    let bindings_rs = out_dir.join("bindings.rs");
    generate_rust_bindings(&header_dir, &bindings_rs);

    let cs_out = workspace_root
        .join("src")
        .join(CSHARP_PROJECT)
        .join("Generated")
        .join(format!("{CSHARP_CLASS}.g.cs"));
    generate_csharp_bindings(&bindings_rs, &cs_out);

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", header_dir.display());
}

fn generate_rust_bindings(header_dir: &Path, out: &Path) {
    let bindings = bindgen::Builder::default()
        .header(header_dir.join("lua.h").to_string_lossy())
        .header(header_dir.join("lualib.h").to_string_lossy())
        .header(header_dir.join("lauxlib.h").to_string_lossy())
        // NOTE: luajit.h is generated by buildvm and not checked in. JIT-only
        // entry points (luaJIT_setmode, luaJIT_profile_*) are intentionally
        // skipped here; they will be wired in once buildvm is run.
        .clang_arg(format!("-I{}", header_dir.display()))
        .allowlist_function("lua_.*")
        .allowlist_function("luaL_.*")
        .allowlist_function("luaopen_.*")
        .allowlist_function("luaJIT_.*")
        .allowlist_type("lua_.*")
        .allowlist_type("luaL_.*")
        .allowlist_var("LUA_.*")
        .allowlist_var("LUAL_.*")
        .allowlist_var("LUAJIT_.*")
        .layout_tests(false)
        .generate()
        .expect("bindgen failed");
    bindings.write_to_file(out).expect("write bindings.rs");
}

fn generate_csharp_bindings(bindings_rs: &Path, out_cs: &Path) {
    std::fs::create_dir_all(out_cs.parent().unwrap()).expect("mkdir Generated/");
    csbindgen::Builder::default()
        .input_bindgen_file(bindings_rs)
        .csharp_dll_name(FLAVOR)
        .csharp_namespace(CSHARP_NAMESPACE)
        .csharp_class_name(CSHARP_CLASS)
        .generate_csharp_file(out_cs)
        .expect("csbindgen failed");
}
