<Project>
  <PropertyGroup>
    <!-- NuGet Packaging -->
    <PackageVersion>0.0.2</PackageVersion>
    <Authors>nuskey</Authors>
    <Copyright>© Yusuke Nakada</Copyright>
    <PackageProjectUrl>https://github.com/nuskey8/NuLua</PackageProjectUrl>
    <RepositoryUrl>$(PackageProjectUrl)</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
