<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <!-- Not include this dll, only native dlls. -->
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <IncludeContentInPack>true</IncludeContentInPack>
    <NoWarn>$(NoWarn);NU5100;NU5128</NoWarn>
    <Description>lua55 native runtime for osx-x64.</Description>

    <!-- NuGet Packaging -->
    <IsPackable>true</IsPackable>
    <PackageTags>lua;luau;luajit</PackageTags>
    <Description>NuLua Runtime for Lua 5.5 macOS x64</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="README.md" />
    <None Include="..\..\assets\icon.png" Pack="true" PackagePath="icon.png" />
    <EmbeddedResource Include="..\..\LICENSE" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="runtimes\**" />
    <None
      Include="runtimes\osx-x64\native\liblua55.dylib"
      PackagePath="runtimes\osx-x64\native\"
      Pack="true"
    >
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
