<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net11.0;net10.0;netstandard2.1</TargetFrameworks>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <!-- NuGet Packaging -->
    <IsPackable>true</IsPackable>
    <PackageTags>lua;luau;luajit</PackageTags>
    <Description>NuLua Low-Level Bindings for Lua5.1</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Polyfills\CLong.cs" Link="Polyfills\CLong.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="README.md" />
    <EmbeddedResource Include="..\..\LICENSE" />
  </ItemGroup>
</Project>
