<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <!-- Not include this dll, only native dlls. -->
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <IncludeContentInPack>true</IncludeContentInPack>
    <NoWarn>$(NoWarn);NU5100;NU5128</NoWarn>
    <Description>luau native runtimes for NuLua.Interop.Luau.</Description>

    <!-- NuGet -->
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="runtimes\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="NuLua.Runtime.Luau.win-x64.csproj" />
    <ProjectReference Include="NuLua.Runtime.Luau.win-arm64.csproj" />
    <ProjectReference Include="NuLua.Runtime.Luau.linux-x64.csproj" />
    <ProjectReference Include="NuLua.Runtime.Luau.linux-arm64.csproj" />
    <ProjectReference Include="NuLua.Runtime.Luau.osx-x64.csproj" />
    <ProjectReference Include="NuLua.Runtime.Luau.osx-arm64.csproj" />
  </ItemGroup>
</Project>
