/* automatically generated by csbindgen */

#[allow(unused)]
use ::std::os::raw::*;

use crate::luajit::*;


#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_newstate(
    f: lua_Alloc,
    ud: *mut c_void
) -> *mut lua_State
{
    lua_newstate(
        f,
        ud
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_close(
    L: *mut lua_State
)
{
    lua_close(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_newthread(
    L: *mut lua_State
) -> *mut lua_State
{
    lua_newthread(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_atpanic(
    L: *mut lua_State,
    panicf: lua_CFunction
) -> lua_CFunction
{
    lua_atpanic(
        L,
        panicf
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_gettop(
    L: *mut lua_State
) -> c_int
{
    lua_gettop(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_settop(
    L: *mut lua_State,
    idx: c_int
)
{
    lua_settop(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_pushvalue(
    L: *mut lua_State,
    idx: c_int
)
{
    lua_pushvalue(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_remove(
    L: *mut lua_State,
    idx: c_int
)
{
    lua_remove(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_insert(
    L: *mut lua_State,
    idx: c_int
)
{
    lua_insert(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_replace(
    L: *mut lua_State,
    idx: c_int
)
{
    lua_replace(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_checkstack(
    L: *mut lua_State,
    sz: c_int
) -> c_int
{
    lua_checkstack(
        L,
        sz
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_xmove(
    from: *mut lua_State,
    to: *mut lua_State,
    n: c_int
)
{
    lua_xmove(
        from,
        to,
        n
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_isnumber(
    L: *mut lua_State,
    idx: c_int
) -> c_int
{
    lua_isnumber(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_isstring(
    L: *mut lua_State,
    idx: c_int
) -> c_int
{
    lua_isstring(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_iscfunction(
    L: *mut lua_State,
    idx: c_int
) -> c_int
{
    lua_iscfunction(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_isuserdata(
    L: *mut lua_State,
    idx: c_int
) -> c_int
{
    lua_isuserdata(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_type(
    L: *mut lua_State,
    idx: c_int
) -> c_int
{
    lua_type(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_typename(
    L: *mut lua_State,
    tp: c_int
) -> *const c_char
{
    lua_typename(
        L,
        tp
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_equal(
    L: *mut lua_State,
    idx1: c_int,
    idx2: c_int
) -> c_int
{
    lua_equal(
        L,
        idx1,
        idx2
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_rawequal(
    L: *mut lua_State,
    idx1: c_int,
    idx2: c_int
) -> c_int
{
    lua_rawequal(
        L,
        idx1,
        idx2
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_lessthan(
    L: *mut lua_State,
    idx1: c_int,
    idx2: c_int
) -> c_int
{
    lua_lessthan(
        L,
        idx1,
        idx2
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_tonumber(
    L: *mut lua_State,
    idx: c_int
) -> lua_Number
{
    lua_tonumber(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_tointeger(
    L: *mut lua_State,
    idx: c_int
) -> lua_Integer
{
    lua_tointeger(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_toboolean(
    L: *mut lua_State,
    idx: c_int
) -> c_int
{
    lua_toboolean(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_tolstring(
    L: *mut lua_State,
    idx: c_int,
    len: *mut usize
) -> *const c_char
{
    lua_tolstring(
        L,
        idx,
        len
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_objlen(
    L: *mut lua_State,
    idx: c_int
) -> usize
{
    lua_objlen(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_tocfunction(
    L: *mut lua_State,
    idx: c_int
) -> lua_CFunction
{
    lua_tocfunction(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_touserdata(
    L: *mut lua_State,
    idx: c_int
) -> *mut c_void
{
    lua_touserdata(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_tothread(
    L: *mut lua_State,
    idx: c_int
) -> *mut lua_State
{
    lua_tothread(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_topointer(
    L: *mut lua_State,
    idx: c_int
) -> *const c_void
{
    lua_topointer(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_pushnil(
    L: *mut lua_State
)
{
    lua_pushnil(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_pushnumber(
    L: *mut lua_State,
    n: lua_Number
)
{
    lua_pushnumber(
        L,
        n
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_pushinteger(
    L: *mut lua_State,
    n: lua_Integer
)
{
    lua_pushinteger(
        L,
        n
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_pushlstring(
    L: *mut lua_State,
    s: *const c_char,
    l: usize
)
{
    lua_pushlstring(
        L,
        s,
        l
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_pushstring(
    L: *mut lua_State,
    s: *const c_char
)
{
    lua_pushstring(
        L,
        s
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_pushvfstring(
    L: *mut lua_State,
    fmt: *const c_char,
    argp: va_list
) -> *const c_char
{
    lua_pushvfstring(
        L,
        fmt,
        argp
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_pushfstring(
    L: *mut lua_State,
    fmt: *const c_char
) -> *const c_char
{
    lua_pushfstring(
        L,
        fmt
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_pushcclosure(
    L: *mut lua_State,
    fn_: lua_CFunction,
    n: c_int
)
{
    lua_pushcclosure(
        L,
        fn_,
        n
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_pushboolean(
    L: *mut lua_State,
    b: c_int
)
{
    lua_pushboolean(
        L,
        b
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_pushlightuserdata(
    L: *mut lua_State,
    p: *mut c_void
)
{
    lua_pushlightuserdata(
        L,
        p
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_pushthread(
    L: *mut lua_State
) -> c_int
{
    lua_pushthread(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_gettable(
    L: *mut lua_State,
    idx: c_int
)
{
    lua_gettable(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_getfield(
    L: *mut lua_State,
    idx: c_int,
    k: *const c_char
)
{
    lua_getfield(
        L,
        idx,
        k
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_rawget(
    L: *mut lua_State,
    idx: c_int
)
{
    lua_rawget(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_rawgeti(
    L: *mut lua_State,
    idx: c_int,
    n: c_int
)
{
    lua_rawgeti(
        L,
        idx,
        n
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_createtable(
    L: *mut lua_State,
    narr: c_int,
    nrec: c_int
)
{
    lua_createtable(
        L,
        narr,
        nrec
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_newuserdata(
    L: *mut lua_State,
    sz: usize
) -> *mut c_void
{
    lua_newuserdata(
        L,
        sz
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_getmetatable(
    L: *mut lua_State,
    objindex: c_int
) -> c_int
{
    lua_getmetatable(
        L,
        objindex
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_getfenv(
    L: *mut lua_State,
    idx: c_int
)
{
    lua_getfenv(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_settable(
    L: *mut lua_State,
    idx: c_int
)
{
    lua_settable(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_setfield(
    L: *mut lua_State,
    idx: c_int,
    k: *const c_char
)
{
    lua_setfield(
        L,
        idx,
        k
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_rawset(
    L: *mut lua_State,
    idx: c_int
)
{
    lua_rawset(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_rawseti(
    L: *mut lua_State,
    idx: c_int,
    n: c_int
)
{
    lua_rawseti(
        L,
        idx,
        n
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_setmetatable(
    L: *mut lua_State,
    objindex: c_int
) -> c_int
{
    lua_setmetatable(
        L,
        objindex
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_setfenv(
    L: *mut lua_State,
    idx: c_int
) -> c_int
{
    lua_setfenv(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_call(
    L: *mut lua_State,
    nargs: c_int,
    nresults: c_int
)
{
    lua_call(
        L,
        nargs,
        nresults
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_pcall(
    L: *mut lua_State,
    nargs: c_int,
    nresults: c_int,
    errfunc: c_int
) -> c_int
{
    lua_pcall(
        L,
        nargs,
        nresults,
        errfunc
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_cpcall(
    L: *mut lua_State,
    func: lua_CFunction,
    ud: *mut c_void
) -> c_int
{
    lua_cpcall(
        L,
        func,
        ud
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_load(
    L: *mut lua_State,
    reader: lua_Reader,
    dt: *mut c_void,
    chunkname: *const c_char
) -> c_int
{
    lua_load(
        L,
        reader,
        dt,
        chunkname
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_dump(
    L: *mut lua_State,
    writer: lua_Writer,
    data: *mut c_void
) -> c_int
{
    lua_dump(
        L,
        writer,
        data
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_yield(
    L: *mut lua_State,
    nresults: c_int
) -> c_int
{
    lua_yield(
        L,
        nresults
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_resume(
    L: *mut lua_State,
    narg: c_int
) -> c_int
{
    lua_resume(
        L,
        narg
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_status(
    L: *mut lua_State
) -> c_int
{
    lua_status(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_gc(
    L: *mut lua_State,
    what: c_int,
    data: c_int
) -> c_int
{
    lua_gc(
        L,
        what,
        data
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_error(
    L: *mut lua_State
) -> c_int
{
    lua_error(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_next(
    L: *mut lua_State,
    idx: c_int
) -> c_int
{
    lua_next(
        L,
        idx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_concat(
    L: *mut lua_State,
    n: c_int
)
{
    lua_concat(
        L,
        n
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_getallocf(
    L: *mut lua_State,
    ud: *mut *mut c_void
) -> lua_Alloc
{
    lua_getallocf(
        L,
        ud
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_setallocf(
    L: *mut lua_State,
    f: lua_Alloc,
    ud: *mut c_void
)
{
    lua_setallocf(
        L,
        f,
        ud
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_setlevel(
    from: *mut lua_State,
    to: *mut lua_State
)
{
    lua_setlevel(
        from,
        to
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_getstack(
    L: *mut lua_State,
    level: c_int,
    ar: *mut lua_Debug
) -> c_int
{
    lua_getstack(
        L,
        level,
        ar
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_getinfo(
    L: *mut lua_State,
    what: *const c_char,
    ar: *mut lua_Debug
) -> c_int
{
    lua_getinfo(
        L,
        what,
        ar
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_getlocal(
    L: *mut lua_State,
    ar: *const lua_Debug,
    n: c_int
) -> *const c_char
{
    lua_getlocal(
        L,
        ar,
        n
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_setlocal(
    L: *mut lua_State,
    ar: *const lua_Debug,
    n: c_int
) -> *const c_char
{
    lua_setlocal(
        L,
        ar,
        n
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_getupvalue(
    L: *mut lua_State,
    funcindex: c_int,
    n: c_int
) -> *const c_char
{
    lua_getupvalue(
        L,
        funcindex,
        n
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_setupvalue(
    L: *mut lua_State,
    funcindex: c_int,
    n: c_int
) -> *const c_char
{
    lua_setupvalue(
        L,
        funcindex,
        n
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_sethook(
    L: *mut lua_State,
    func: lua_Hook,
    mask: c_int,
    count: c_int
) -> c_int
{
    lua_sethook(
        L,
        func,
        mask,
        count
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_gethook(
    L: *mut lua_State
) -> lua_Hook
{
    lua_gethook(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_gethookmask(
    L: *mut lua_State
) -> c_int
{
    lua_gethookmask(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_gethookcount(
    L: *mut lua_State
) -> c_int
{
    lua_gethookcount(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_upvalueid(
    L: *mut lua_State,
    idx: c_int,
    n: c_int
) -> *mut c_void
{
    lua_upvalueid(
        L,
        idx,
        n
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_upvaluejoin(
    L: *mut lua_State,
    idx1: c_int,
    n1: c_int,
    idx2: c_int,
    n2: c_int
)
{
    lua_upvaluejoin(
        L,
        idx1,
        n1,
        idx2,
        n2
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_loadx(
    L: *mut lua_State,
    reader: lua_Reader,
    dt: *mut c_void,
    chunkname: *const c_char,
    mode: *const c_char
) -> c_int
{
    lua_loadx(
        L,
        reader,
        dt,
        chunkname,
        mode
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_version(
    L: *mut lua_State
) -> *const lua_Number
{
    lua_version(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_copy(
    L: *mut lua_State,
    fromidx: c_int,
    toidx: c_int
)
{
    lua_copy(
        L,
        fromidx,
        toidx
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_tonumberx(
    L: *mut lua_State,
    idx: c_int,
    isnum: *mut c_int
) -> lua_Number
{
    lua_tonumberx(
        L,
        idx,
        isnum
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_tointegerx(
    L: *mut lua_State,
    idx: c_int,
    isnum: *mut c_int
) -> lua_Integer
{
    lua_tointegerx(
        L,
        idx,
        isnum
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_lua_isyieldable(
    L: *mut lua_State
) -> c_int
{
    lua_isyieldable(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaopen_base(
    L: *mut lua_State
) -> c_int
{
    luaopen_base(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaopen_math(
    L: *mut lua_State
) -> c_int
{
    luaopen_math(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaopen_string(
    L: *mut lua_State
) -> c_int
{
    luaopen_string(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaopen_table(
    L: *mut lua_State
) -> c_int
{
    luaopen_table(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaopen_io(
    L: *mut lua_State
) -> c_int
{
    luaopen_io(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaopen_os(
    L: *mut lua_State
) -> c_int
{
    luaopen_os(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaopen_package(
    L: *mut lua_State
) -> c_int
{
    luaopen_package(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaopen_debug(
    L: *mut lua_State
) -> c_int
{
    luaopen_debug(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaopen_bit(
    L: *mut lua_State
) -> c_int
{
    luaopen_bit(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaopen_jit(
    L: *mut lua_State
) -> c_int
{
    luaopen_jit(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaopen_ffi(
    L: *mut lua_State
) -> c_int
{
    luaopen_ffi(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaopen_string_buffer(
    L: *mut lua_State
) -> c_int
{
    luaopen_string_buffer(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_openlibs(
    L: *mut lua_State
)
{
    luaL_openlibs(
        L
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_openlib(
    L: *mut lua_State,
    libname: *const c_char,
    l: *const luaL_Reg,
    nup: c_int
)
{
    luaL_openlib(
        L,
        libname,
        l,
        nup
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_register(
    L: *mut lua_State,
    libname: *const c_char,
    l: *const luaL_Reg
)
{
    luaL_register(
        L,
        libname,
        l
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_getmetafield(
    L: *mut lua_State,
    obj: c_int,
    e: *const c_char
) -> c_int
{
    luaL_getmetafield(
        L,
        obj,
        e
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_callmeta(
    L: *mut lua_State,
    obj: c_int,
    e: *const c_char
) -> c_int
{
    luaL_callmeta(
        L,
        obj,
        e
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_typerror(
    L: *mut lua_State,
    narg: c_int,
    tname: *const c_char
) -> c_int
{
    luaL_typerror(
        L,
        narg,
        tname
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_argerror(
    L: *mut lua_State,
    numarg: c_int,
    extramsg: *const c_char
) -> c_int
{
    luaL_argerror(
        L,
        numarg,
        extramsg
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_checklstring(
    L: *mut lua_State,
    numArg: c_int,
    l: *mut usize
) -> *const c_char
{
    luaL_checklstring(
        L,
        numArg,
        l
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_optlstring(
    L: *mut lua_State,
    numArg: c_int,
    def: *const c_char,
    l: *mut usize
) -> *const c_char
{
    luaL_optlstring(
        L,
        numArg,
        def,
        l
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_checknumber(
    L: *mut lua_State,
    numArg: c_int
) -> lua_Number
{
    luaL_checknumber(
        L,
        numArg
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_optnumber(
    L: *mut lua_State,
    nArg: c_int,
    def: lua_Number
) -> lua_Number
{
    luaL_optnumber(
        L,
        nArg,
        def
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_checkinteger(
    L: *mut lua_State,
    numArg: c_int
) -> lua_Integer
{
    luaL_checkinteger(
        L,
        numArg
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_optinteger(
    L: *mut lua_State,
    nArg: c_int,
    def: lua_Integer
) -> lua_Integer
{
    luaL_optinteger(
        L,
        nArg,
        def
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_checkstack(
    L: *mut lua_State,
    sz: c_int,
    msg: *const c_char
)
{
    luaL_checkstack(
        L,
        sz,
        msg
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_checktype(
    L: *mut lua_State,
    narg: c_int,
    t: c_int
)
{
    luaL_checktype(
        L,
        narg,
        t
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_checkany(
    L: *mut lua_State,
    narg: c_int
)
{
    luaL_checkany(
        L,
        narg
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_newmetatable(
    L: *mut lua_State,
    tname: *const c_char
) -> c_int
{
    luaL_newmetatable(
        L,
        tname
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_checkudata(
    L: *mut lua_State,
    ud: c_int,
    tname: *const c_char
) -> *mut c_void
{
    luaL_checkudata(
        L,
        ud,
        tname
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_where(
    L: *mut lua_State,
    lvl: c_int
)
{
    luaL_where(
        L,
        lvl
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_error(
    L: *mut lua_State,
    fmt: *const c_char
) -> c_int
{
    luaL_error(
        L,
        fmt
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_checkoption(
    L: *mut lua_State,
    narg: c_int,
    def: *const c_char,
    lst: *const *const c_char
) -> c_int
{
    luaL_checkoption(
        L,
        narg,
        def,
        lst
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_ref(
    L: *mut lua_State,
    t: c_int
) -> c_int
{
    luaL_ref(
        L,
        t
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_unref(
    L: *mut lua_State,
    t: c_int,
    ref_: c_int
)
{
    luaL_unref(
        L,
        t,
        ref_
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_loadfile(
    L: *mut lua_State,
    filename: *const c_char
) -> c_int
{
    luaL_loadfile(
        L,
        filename
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_loadbuffer(
    L: *mut lua_State,
    buff: *const c_char,
    sz: usize,
    name: *const c_char
) -> c_int
{
    luaL_loadbuffer(
        L,
        buff,
        sz,
        name
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_loadstring(
    L: *mut lua_State,
    s: *const c_char
) -> c_int
{
    luaL_loadstring(
        L,
        s
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_newstate(

) -> *mut lua_State
{
    luaL_newstate(

    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_gsub(
    L: *mut lua_State,
    s: *const c_char,
    p: *const c_char,
    r: *const c_char
) -> *const c_char
{
    luaL_gsub(
        L,
        s,
        p,
        r
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_findtable(
    L: *mut lua_State,
    idx: c_int,
    fname: *const c_char,
    szhint: c_int
) -> *const c_char
{
    luaL_findtable(
        L,
        idx,
        fname,
        szhint
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_fileresult(
    L: *mut lua_State,
    stat: c_int,
    fname: *const c_char
) -> c_int
{
    luaL_fileresult(
        L,
        stat,
        fname
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_execresult(
    L: *mut lua_State,
    stat: c_int
) -> c_int
{
    luaL_execresult(
        L,
        stat
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_loadfilex(
    L: *mut lua_State,
    filename: *const c_char,
    mode: *const c_char
) -> c_int
{
    luaL_loadfilex(
        L,
        filename,
        mode
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_loadbufferx(
    L: *mut lua_State,
    buff: *const c_char,
    sz: usize,
    name: *const c_char,
    mode: *const c_char
) -> c_int
{
    luaL_loadbufferx(
        L,
        buff,
        sz,
        name,
        mode
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_traceback(
    L: *mut lua_State,
    L1: *mut lua_State,
    msg: *const c_char,
    level: c_int
)
{
    luaL_traceback(
        L,
        L1,
        msg,
        level
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_setfuncs(
    L: *mut lua_State,
    l: *const luaL_Reg,
    nup: c_int
)
{
    luaL_setfuncs(
        L,
        l,
        nup
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_pushmodule(
    L: *mut lua_State,
    modname: *const c_char,
    sizehint: c_int
)
{
    luaL_pushmodule(
        L,
        modname,
        sizehint
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_testudata(
    L: *mut lua_State,
    ud: c_int,
    tname: *const c_char
) -> *mut c_void
{
    luaL_testudata(
        L,
        ud,
        tname
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_setmetatable(
    L: *mut lua_State,
    tname: *const c_char
)
{
    luaL_setmetatable(
        L,
        tname
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_buffinit(
    L: *mut lua_State,
    B: *mut luaL_Buffer
)
{
    luaL_buffinit(
        L,
        B
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_prepbuffer(
    B: *mut luaL_Buffer
) -> *mut c_char
{
    luaL_prepbuffer(
        B
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_addlstring(
    B: *mut luaL_Buffer,
    s: *const c_char,
    l: usize
)
{
    luaL_addlstring(
        B,
        s,
        l
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_addstring(
    B: *mut luaL_Buffer,
    s: *const c_char
)
{
    luaL_addstring(
        B,
        s
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_addvalue(
    B: *mut luaL_Buffer
)
{
    luaL_addvalue(
        B
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_luaL_pushresult(
    B: *mut luaL_Buffer
)
{
    luaL_pushresult(
        B
    )
}

    