<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <!-- Not include this dll, only native dlls. -->
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <IncludeContentInPack>true</IncludeContentInPack>
    <NoWarn>$(NoWarn);NU5100;NU5128</NoWarn>
    <Description>luajit native runtime for osx-arm64.</Description>

    <!-- NuGet -->
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="runtimes\**" />
    <None
      Include="runtimes\osx-arm64\native\libluajit.dylib"
      PackagePath="runtimes\osx-arm64\native\"
      Pack="true"
      Condition="Exists('runtimes\osx-arm64\native\libluajit.dylib')"
    >
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
