<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net11.0;net10.0;netstandard2.1</TargetFrameworks>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <!-- NuGet Packaging -->
    <IsPackable>true</IsPackable>
    <PackageTags>lua;luau;luajit</PackageTags>
    <Description>NuLua High-level API for Lua 5.3</Description>

    <!-- Code Generation Parameters -->
    <CodeGenName>Lua53</CodeGenName>
    <CodeGenVersion>503</CodeGenVersion>
    <CodeGenProject>$(MSBuildThisFileDirectory)..\..\tools\CodeGen\CodeGen.csproj</CodeGenProject>
    <CodeGenTemplateDir>$(MSBuildThisFileDirectory)..\..\tools\CodeGen\Templates\Lua52Plus</CodeGenTemplateDir>
    <CodeGenCommonTemplateDir>$(MSBuildThisFileDirectory)..\..\tools\CodeGen\Templates\Common</CodeGenCommonTemplateDir>
    <CodeGenOutputDir>$(MSBuildThisFileDirectory)Generated</CodeGenOutputDir>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NuLua\NuLua.csproj" />
    <ProjectReference Include="..\NuLua.Runtime.Lua53\NuLua.Runtime.Lua53.csproj" />
    <ProjectReference Include="..\NuLua.Interop.Lua53\NuLua.Interop.Lua53.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="README.md" />
    <None Include="..\..\assets\icon.png" Pack="true" PackagePath="icon.png" />
    <EmbeddedResource Include="..\..\LICENSE" />
  </ItemGroup>

  <ItemGroup>
    <CodeGenTemplate Include="$(CodeGenTemplateDir)\*.scriban-cs" />
    <CodeGenTemplate Include="$(CodeGenCommonTemplateDir)\*.scriban-cs" />
  </ItemGroup>

  <Target Name="BuildCodeGen" BeforeTargets="RunCodeGen" Condition="'$(DesignTimeBuild)' != 'true'">
    <MSBuild
      Projects="$(CodeGenProject)"
      Targets="Build"
      Properties="Configuration=$(Configuration)"
      RemoveProperties="TargetFramework"
    />
  </Target>

  <Target
    Name="RunCodeGen"
    BeforeTargets="CoreCompile"
    Condition="'$(DesignTimeBuild)' != 'true'"
    Inputs="@(CodeGenTemplate)"
    Outputs="$(CodeGenOutputDir)\$(CodeGenName)State.g.cs;$(CodeGenOutputDir)\$(CodeGenName)State.Common.g.cs"
  >
    <MakeDir Directories="$(CodeGenOutputDir)" />
    <Exec Command="dotnet run --project &quot;$(CodeGenProject)&quot; --configuration $(Configuration) --no-build -- --name $(CodeGenName) --version $(CodeGenVersion) --common-template-dir &quot;$(CodeGenCommonTemplateDir)&quot; --dialect-template-dir &quot;$(CodeGenTemplateDir)&quot; --output-dir &quot;$(CodeGenOutputDir)&quot;" />
  </Target>

</Project>
