<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <!-- Not include this dll, only native dlls. -->
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <IncludeContentInPack>true</IncludeContentInPack>
    <NoWarn>$(NoWarn);NU5100;NU5128</NoWarn>
    <Description>lua53 native runtime for linux-x64.</Description>

    <!-- NuGet -->
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="runtimes\**" />
    <None Include="runtimes\linux-x64\native\liblua53.so" PackagePath="runtimes\linux-x64\native\" Pack="true" Condition="Exists('runtimes\linux-x64\native\liblua53.so')">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
